# Created by trellis-cli v1.7.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  179eventos.com.br:
    site_hosts:
    - canonical: 179eventos.com.br
      redirects:
      - www.179eventos.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/179eventos.com.br.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
